### ISSUE TITLE
BBC Micro:Bit - typing inconsistency

### ISSUE THREAD

**Issue by farxinu** [mit-cml/iot-website-source#44]
Inconsistency in how the Micro:Bit is referenced. 
Microbit and BBC:Microbit have both been typed on the website. 
I believe the correct format is BBC Micro:Bit.

**Comment by ewpatton** [comment]
The capitalization and naming convention on the Micro:bit Foundation's website isn't always consistent on the matter, either. On the [about page](http://microbit.org/about/) they refer to it as the "BBC micro:bit" and sometimes drop the BBC part of it (I think now that there are more partners ex. the BBC). There are also capitalization and dropping of the BBC qualifier on their own (presumably curated) list of [example projects](http://microbit.org/ideas/). I think for consistency we introduce it as the BBC micro:bit and then thereafter refer to it simply as the micro:bit, except when starting a sentence or in code in which case it is Micro:bit (Microbit in code due to identifier rules). If only because pronouncing BBC is a mouthful.

**Comment by ewpatton** [comment]
I'm going to take this issue because it also implies updating all of the extension documentation in the sources and rebuilding the extension.
